### ISSUE TITLE
Installation not successfull on Raspbian

### ISSUE THREAD

**Issue by casa97074** [Elecrow-RD/Elecrow-LCD101#4]
I've got the problem, that I can't install the driver on a Raspberry Pi. I got the driver (github.com/Electrow-keen/Elecrow-LCD101), but I can't install it. If I run "sudo ./Electrow-LCD101" (in the right folder), I get : "command not found"
Has anyone a solution for this problem?
Thanks a lot!

**Comment by gmbo** [comment]
you must set the x flag with
chmod +x Electrow-LCD101

**Comment by SachDew** [comment]
I entered the chmod command and tried, Got the error as
bash: sudo./Elecrow-LCD101: No such  file or directory

**Comment by SachDew** [comment]
![rasp](https://user-images.githubusercontent.com/96802507/147710659-4159539f-df7b-43bb-b33e-798d961466b2.jpg)
has anyone a solution for this problem

**Comment by gmbo** [comment]
you forget a blank after sudo

**Comment by SachDew** [comment]
Thanks

**Comment by SachDew** [comment]
Is the raspibian  suppose to detect the screen size its own when connected with the 10.1 screen ? because in mine it was flashing and not working properly. But its working with a bigger monitor. I ran the above program and still no difference.

**Comment by SachDew** [comment]
im using a Raspberry pi 4 model b 4gb one.

**Comment by Elecrow-RD** [comment]
Driver was updated, this should solve the problem.
